def main9(s: str, t: str):

    positions = []
    for i in range(len(s) - len(t) + 1):
        if s[i:i+len(t)] == t:
            positions.append(i + 1)
    return ' '.join(map(str, positions))

if __name__ == '__main__':
    print(main9("CAAGGGGCCGGAAGGGGCAAACAAGGGGCAAAGGGGCATGAAAGGGGCAAAAGGGGCAAGGGGCCCGAAGGGGCTTAAAAGGGGCGCGGTTTAAGGGGCAAGGGGCCAAGGGGCGAAGGGGCAAGGGGCCAAGGGGCAAAGGGGCAGAAGGGGCAGGAAGGGGCGAAGGGGCGTTAAGGGGCGATAGGGGCTAAGGGGCAAGGGGCTTCGTCGAATAAGGGGCGAAGGGGCAGAGCCAAGGGGCGCTCCATCAAGGGGCACACAAAGGGGCCCACCAAGGGGCCTCGTAAGGGGCGCTCCTAAGGGGCTAAGGGGCCAACGACTGCAATCAAGGGGCGCTAGAAATTCAAGGGGCCAAGGGGCAGGAAGGGGCTAAGGGGCTAACAGAAGGGGCGGAAGGGGCAAGGGGCAAGGGGCAAGGGGCATGAAGGGGCAAGGGGCAAGGGGCCTGCTAAGGGGCAAGGGGCTAAGGGGCAAGGGGCGAAGGGGCCTAAGGGGCCAAGGGGCGCCGAAGGGGCCTTAAAGGGGCCAAGGGGCTAAGGGGCAAGGGGCTGCATAAGGGGCAAAGGGGCCAAGGGGCAAGGGGCAAAAGGGGCGTATCACGCAAGGGGCCAAGGGGCAAGGGGCAAGGGGCGTGATTTAAGGGGCTAAGGGGCCGGGAAGGGGCATAAGGGGCAAGGGGCAAGGGGCGTTATAAGGGGCAAGGGGCCAAGGGGCAAAGGGGCAGAAAGGGGCCCAAGGGGCTTATGAGCCAAAGGGGCGGACACAAGGGGCAAAGGGGCTAAGGGGCCTAAGGGGCAAGGGGCAAGGGGCTGAAGGGGCTAAAGGGGCAAGGGGCAAGGGGCCGATGTGGGGAAGGGGCAAGGGGC", "AAGGGGCAA"))